# Generated by Django 4.2 on 2026-07-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Título de la tarea"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("simple", "Simple (Blanco)"),
                            ("intermedio", "Intermedio (Amarillo)"),
                            ("urgente", "Urgente (Rojo)"),
                        ],
                        default="simple",
                        max_length=20,
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Completada"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarea",
                "verbose_name_plural": "Tareas",
                "ordering": ["-created_at"],
            },
        ),
    ]
